name: Hello World!


on: 
  push:
    branches:
       - master

jobs: 
  Hello_World_Job:
      runs-on: ubuntu-23.04
      steps:
        - name: Say hello
          run: | 
              echo 'hello world'
        
